// <auto-generated/>
// Generated by tools/GeneratePoses from the published OpenAPI document. Do not edit by hand.
// Run: dotnet run --project tools/GeneratePoses
#pragma warning disable CS1591 // pose-name constants are self-describing
namespace Createrington.SkinApi;

/// <summary>
/// Poses known to the SDK at build time. <see cref="SkinApiClient.RenderAsync"/>
/// accepts any pose string, so server-added poses keep working without an SDK
/// upgrade; these constants exist for discoverability and compile-time names.
/// </summary>
public static class KnownPoses
{
    public const string Britzel = "britzel";
    public const string Callout = "callout";
    public const string Cheer = "cheer";
    public const string Confidence = "confidence";
    public const string Crossed = "crossed";
    public const string Crouching = "crouching";
    public const string Curl = "curl";
    public const string Cute = "cute";
    public const string Dab = "dab";
    public const string Dead = "dead";
    public const string Defeat = "defeat";
    public const string Friendship = "friendship";
    public const string Gaze = "gaze";
    public const string Handstand = "handstand";
    public const string Idle = "idle";
    public const string Idol = "idol";
    public const string Kneel = "kneel";
    public const string Lounge = "lounge";
    public const string Mojavatar = "mojavatar";
    public const string Ninja = "ninja";
    public const string Point = "point";
    public const string Ponder = "ponder";
    public const string Relaxed = "relaxed";
    public const string Scared = "scared";
    public const string Sprint = "sprint";
    public const string Tiptoe = "tiptoe";
    public const string Victory = "victory";
    public const string Wave = "wave";
    public const string Zombie = "zombie";

    /// <summary>All poses known to the SDK at build time, sorted alphabetically.</summary>
    public static readonly IReadOnlyList<string> All = new[]
    {
        Britzel,
        Callout,
        Cheer,
        Confidence,
        Crossed,
        Crouching,
        Curl,
        Cute,
        Dab,
        Dead,
        Defeat,
        Friendship,
        Gaze,
        Handstand,
        Idle,
        Idol,
        Kneel,
        Lounge,
        Mojavatar,
        Ninja,
        Point,
        Ponder,
        Relaxed,
        Scared,
        Sprint,
        Tiptoe,
        Victory,
        Wave,
        Zombie,
    };

    /// <summary>Returns a uniformly random known pose name.</summary>
    public static string Random() =>
        All[System.Random.Shared.Next(All.Count)];
}
