// Regenerates src/Createrington.SkinApi/KnownPoses.cs from the published OpenAPI
// document. Pose names come from the `pose` query-parameter enum on
// POST /v1/render. By default it fetches the live spec; pass a file path or URL
// to override (for testing or offline runs). No spec file is written to disk.
//
//   dotnet run --project tools/GeneratePoses [openapi.json | https://host/v1/openapi.json]
using System.Runtime.CompilerServices;
using System.Text;
using System.Text.Json;

const string DefaultSpecUrl = "https://api.createrington.com/v1/openapi.json";

static string ProjectDir([CallerFilePath] string path = "") => Path.GetDirectoryName(path)!;

var outFile = Path.GetFullPath(
    Path.Combine(ProjectDir(), "..", "..", "src", "Createrington.SkinApi", "KnownPoses.cs"));

var source = args.Length > 0 && args[0].Length > 0
    ? args[0]
    : Environment.GetEnvironmentVariable("SKIN_API_OPENAPI_URL") is { Length: > 0 } env
        ? env
        : DefaultSpecUrl;

byte[] specBytes;
try
{
    if (File.Exists(source))
    {
        specBytes = File.ReadAllBytes(source);
    }
    else if (source.StartsWith("http://", StringComparison.OrdinalIgnoreCase)
        || source.StartsWith("https://", StringComparison.OrdinalIgnoreCase))
    {
        using var http = new HttpClient { Timeout = TimeSpan.FromSeconds(30) };
        specBytes = http.GetByteArrayAsync(source).GetAwaiter().GetResult();
    }
    else
    {
        Console.Error.WriteLine($"spec source is neither an existing file nor an http(s) URL: {source}");
        return 1;
    }
}
catch (Exception ex) when (ex is HttpRequestException or TaskCanceledException or IOException)
{
    Console.Error.WriteLine($"could not read the OpenAPI document from {source}: {ex.Message}");
    return 1;
}

List<string> names;
try
{
    using var doc = JsonDocument.Parse(specBytes);
    var parameters = doc.RootElement
        .GetProperty("paths")
        .GetProperty("/v1/render")
        .GetProperty("post")
        .GetProperty("parameters");

    var pose = parameters.EnumerateArray()
        .FirstOrDefault(p => p.TryGetProperty("name", out var n) && n.GetString() == "pose");
    if (pose.ValueKind != JsonValueKind.Object)
    {
        Console.Error.WriteLine("no 'pose' query parameter found on POST /v1/render");
        return 1;
    }

    names = pose.GetProperty("schema").GetProperty("enum")
        .EnumerateArray()
        .Select(e => e.GetString())
        .OfType<string>()
        .OrderBy(n => n, StringComparer.Ordinal)
        .ToList();
}
catch (Exception ex) when (ex is JsonException or KeyNotFoundException or InvalidOperationException)
{
    Console.Error.WriteLine($"could not read the pose enum from the OpenAPI document: {ex.Message}");
    return 1;
}

if (names.Count == 0)
{
    Console.Error.WriteLine("the pose enum is empty");
    return 1;
}

static string Pascal(string name)
{
    var sb = new StringBuilder();
    foreach (var segment in name.Split(new[] { '-', '_', ' ' }, StringSplitOptions.RemoveEmptyEntries))
    {
        sb.Append(char.ToUpperInvariant(segment[0])).Append(segment[1..]);
    }

    var ident = sb.ToString();
    var valid = ident.Length > 0
        && (char.IsLetter(ident[0]) || ident[0] == '_')
        && ident.All(c => char.IsLetterOrDigit(c) || c == '_');
    if (!valid)
    {
        throw new InvalidOperationException(
            $"Pose name '{name}' does not map to a valid C# identifier ('{ident}'); update the generator.");
    }

    return ident;
}

var lines = new List<string>
{
    "// <auto-generated/>",
    "// Generated by tools/GeneratePoses from the published OpenAPI document. Do not edit by hand.",
    "// Run: dotnet run --project tools/GeneratePoses",
    "#pragma warning disable CS1591 // pose-name constants are self-describing",
    "namespace Createrington.SkinApi;",
    "",
    "/// <summary>",
    "/// Poses known to the SDK at build time. <see cref=\"SkinApiClient.RenderAsync\"/>",
    "/// accepts any pose string, so server-added poses keep working without an SDK",
    "/// upgrade; these constants exist for discoverability and compile-time names.",
    "/// </summary>",
    "public static class KnownPoses",
    "{",
};
lines.AddRange(names.Select(n => $"    public const string {Pascal(n)} = \"{n}\";"));
lines.Add("");
lines.Add("    /// <summary>All poses known to the SDK at build time, sorted alphabetically.</summary>");
lines.Add("    public static readonly IReadOnlyList<string> All = new[]");
lines.Add("    {");
lines.AddRange(names.Select(n => $"        {Pascal(n)},"));
lines.Add("    };");
lines.Add("");
lines.Add("    /// <summary>Returns a uniformly random known pose name.</summary>");
lines.Add("    public static string Random() =>");
lines.Add("        All[System.Random.Shared.Next(All.Count)];");
lines.Add("}");

File.WriteAllText(outFile, string.Join("\n", lines) + "\n");
Console.WriteLine($"generated {outFile} ({names.Count} poses) from {source}");
return 0;
