name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - dev

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore
        run: dotnet restore Createrington.SkinApi.sln

      - name: Build
        run: dotnet build Createrington.SkinApi.sln -c Release --no-restore

      - name: Test
        run: dotnet test Createrington.SkinApi.sln -c Release --no-build
